global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway-service:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'service-discovery'
    static_configs:
      - targets: ['service-discovery:8761']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  # Adicionar outros serviços conforme necessário