spring.application.name=service-discovery
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka Server Properties
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=20
# Eureka PROD settings
# eureka.instance.lease-renewal-interval-in-seconds=30
# eureka.instance.lease-expiration-duration-in-seconds=90

# RESILIENCE AND METRICS
management.endpoint.health.show-details=always
management.endpoint.metrics.access=read-only
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.tags.application=${spring.application.name}
management.prometheus.metrics.export.enabled=true

# Logs com Trace ID
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]